include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: warning
    prefer_const_declarations: error
    prefer_const_constructors: error

linter:
  rules:
    missing_required_param: true
    prefer_const_declarations: true
    prefer_const_constructors: true